# Generated by Django 4.2.30 on 2026-04-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(verbose_name='房屋面积(㎡)')),
                ('rooms', models.IntegerField(verbose_name='房间数量')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('year', models.IntegerField(verbose_name='建造年份')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='房价(元)')),
                ('district', models.CharField(choices=[('浦东新区', '浦东新区'), ('黄浦区', '黄浦区'), ('徐汇区', '徐汇区'), ('长宁区', '长宁区'), ('静安区', '静安区'), ('普陀区', '普陀区'), ('虹口区', '虹口区'), ('杨浦区', '杨浦区'), ('闵行区', '闵行区'), ('宝山区', '宝山区'), ('嘉定区', '嘉定区'), ('松江区', '松江区'), ('青浦区', '青浦区'), ('奉贤区', '奉贤区'), ('金山区', '金山区'), ('崇明区', '崇明区')], max_length=20, verbose_name='区域')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('status', models.CharField(choices=[('available', '在售'), ('sold', '已售'), ('off', '下架')], default='available', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '房源',
                'verbose_name_plural': '房源',
                'db_table': 'houses',
                'ordering': ['-created_at'],
            },
        ),
    ]
