# Generated by Django 4.2.30 on 2026-05-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(default='', max_length=300, verbose_name='详细地址'),
        ),
        migrations.AddField(
            model_name='house',
            name='bathrooms',
            field=models.IntegerField(default=1, verbose_name='卫生间数量'),
        ),
        migrations.AddField(
            model_name='house',
            name='decoration',
            field=models.CharField(choices=[('毛坯', '毛坯'), ('简装', '简装'), ('精装', '精装'), ('豪装', '豪装')], default='精装', max_length=10, verbose_name='装修情况'),
        ),
        migrations.AddField(
            model_name='house',
            name='halls',
            field=models.IntegerField(default=1, verbose_name='厅数量'),
        ),
        migrations.AddField(
            model_name='house',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='小区名称'),
        ),
        migrations.AddField(
            model_name='house',
            name='orientation',
            field=models.CharField(choices=[('东', '东'), ('南', '南'), ('西', '西'), ('北', '北'), ('东南', '东南'), ('西南', '西南'), ('东北', '东北'), ('西北', '西北')], default='南', max_length=10, verbose_name='朝向'),
        ),
        migrations.AddField(
            model_name='house',
            name='price_per_sqm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(元/㎡)'),
        ),
        migrations.AddField(
            model_name='house',
            name='property_type',
            field=models.CharField(choices=[('住宅', '住宅'), ('公寓', '公寓'), ('别墅', '别墅'), ('商住', '商住'), ('其他', '其他')], default='住宅', max_length=10, verbose_name='房源类型'),
        ),
        migrations.AddField(
            model_name='house',
            name='total_floors',
            field=models.IntegerField(default=1, verbose_name='总楼层'),
        ),
        migrations.AlterField(
            model_name='house',
            name='floor',
            field=models.IntegerField(verbose_name='所在楼层'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总价(元)'),
        ),
    ]
