# Generated by Django 4.2.30 on 2026-05-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_address_house_bathrooms_house_decoration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='district',
            field=models.CharField(max_length=100, verbose_name='小区/区域'),
        ),
    ]
